### ISSUE TITLE
Please upload latest version to NuGet

### ISSUE THREAD

**Issue by Sioma112233** [AdamWhiteHat/BigRational#8]
The only version that was uploaded to NuGet is old.

Please upload the current version =D

**Comment by AdamWhiteHat** [comment]
10-4. Will do. 
However, I am out of town right now and away from my primary development machine. Normally that wouldnt be an issue, but I use a password manager and really long/complex passwords and so wont be able to log in to nuget until I get back home. Plus, I already have scripts written to do just this very thing in a few keystrokes. I will be back in town in 1 week, and then I will be able to do this. If for some reason I haven't done this and closed out this issue in 7 days, please leave another comment to this thread and that will bring this to the top of my inbox and to my attention.

Thank you for bringing this to my attention, and thank you for your interest in my BigRational project.

**Comment by Sioma112233** [comment]
Hi, in the same day I've built your library from source and started using it but encountered bugs which made me just look for an alternative and I found [Rationals](https://github.com/tompazourek/Rationals) =(

**Comment by stewienj** [comment]
Hi @Sioma112233  for the rest of us who follow this project, do you have a description of how to reproduce the bugs you encountered?

**Comment by AdamWhiteHat** [comment]
@Sioma112233 I'm sorry to hear that. Its understandable that you went with a different library if it wasn't working for you. Could you please tell me what sort of problems you encountered or what you didn't like about the experience? All I probably need is just a short description (the code base isn't that big) and I can probably squash the bug(s). This would be greatly appreciated.

Thanks for the link to the other library. It has some interesting features and a slightly different way of interacting with it that gave me some ideas for improving my project.

**Comment by Sioma112233** [comment]
Hi, no problem
when converting a `double` with value 0.0 to a `BigRational` you'll get 1
``` csharp			
double value = 0;
BigRational x = (BigRational) value;
Console.WriteLine(x); // prints 1 and is actually 1
```

from looking a bit at the code I think this problem will also occur with the conversion from a `decimal` type.

I think that that's it, can't remember anything else.

**Comment by AdamWhiteHat** [comment]
@Sioma112233
LOL, what a bug! 

Indeed, the BigRational constructor overload for double and decimal would erroneously set the fractional part (as opposed to the whole number part) to Fraction.One when the value was zero. 

The Fraction constructor when passed a value of zero sets the denominator to BigInteger.One (for a fraction of 0/1, because you cant divide by zero).

This was probably a copy and paste error where I copied the code for the constructor from Fraction but failed to make all the necessary one-off changes.

Thank you for bringing that to my attention.

**Comment by AdamWhiteHat** [comment]
All done!
[https://www.nuget.org/packages/ExtendedNumerics.BigRational/1.1.0.42648](https://www.nuget.org/packages/ExtendedNumerics.BigRational/1.1.0.42648)
